[package]
name = "qmsg-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
qmsg-types.workspace = true
tungstenite = { version = "0.30", default-features = false, features = ["handshake"] }
wit-bindgen = "0.62"

[target.'cfg(any(unix, target_os = "wasi"))'.dependencies]
libc = "0.2"
